# -*- coding: utf-8 -*-
"""classification of pet's face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wg4trIN52kVIHBZ2IbdSlWSJOW-ZmqAk
"""

!pip install tensorflow opencv-python matplotlib

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import shutil
import urllib.request

url = "https://www.robots.ox.ac.uk/~vgg/data/pets/data/images.tar.gz"
urllib.request.urlretrieve(url, "images.tar.gz")
os.makedirs('dataset', exist_ok=True)
!tar -xvzf images.tar.gz -C dataset/

image_dir = "dataset/images"
for filename in os.listdir(image_dir):
    if filename.endswith(".jpg"):
        class_name = filename.split('_')[0]
        class_dir = os.path.join(image_dir, class_name)
        os.makedirs(class_dir, exist_ok=True)
        shutil.move(os.path.join(image_dir, filename), os.path.join(class_dir, filename))

datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,  # Important
    rotation_range=20,
    zoom_range=0.2,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

train_gen = datagen.flow_from_directory(
    image_dir,
    target_size=(128, 128),
    batch_size=32,
    class_mode="categorical",
    subset="training",
    shuffle=True
)

val_gen = datagen.flow_from_directory(
    image_dir,
    target_size=(128, 128),
    batch_size=32,
    class_mode="categorical",
    subset="validation",
    shuffle=False
)

model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.5),  # Helps reduce overfitting
    tf.keras.layers.Dense(train_gen.num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

history = model.fit(train_gen, validation_data=val_gen, epochs=20, callbacks=[early_stop])

plt.plot(history.history['accuracy'], label='train accuracy')
plt.plot(history.history['val_accuracy'], label='val accuracy')
plt.legend()
plt.title('Training vs Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.grid(True)
plt.show()

